Models/Wedding.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema; // need this when doing NotMapped
namespace WeddingPlanner.Models;
public class Wedding
{
    [Key]
    public int WeddingId {get;set;}

    [Required(ErrorMessage = "Name of one wedder is required")]
    [Display(Name = "Wedder One")]
    public string WedderOne {get;set;}

    [Required(ErrorMessage = "Name of one wedder is required")]
    [Display(Name = "Wedder Two")]
    public string WedderTwo {get;set;}

    [Required(ErrorMessage = "Wedding date is required")]
    [Display(Name = "Wedding Date")]
    [DataType(DataType.Date)]
    [FutureDate]
    public DateTime WeddingDate {get;set;}

    [Required(ErrorMessage = "Wedding address is required")]
    [Display(Name = "Wedding Address")]
    public string WeddingAddress {get;set;}

    public DateTime CreatedAt {get;set;} = DateTime.Now;

    public DateTime UpdatedAt {get;set;} = DateTime.Now;

    public int UserId {get;set;}
    public User? WeddingCreator {get;set;}

    public List<UserWeddingParticipation> WeddingParticipants {get;set;} = new List<UserWeddingParticipation>(); // added for many to many
}


public class FutureDateAttribute : ValidationAttribute
{
    // Need the question marks to account for any possible null values
    protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
    {
        // the following if statement will help pass the validator so that it continues to the next step because you cannot check something that is empty
        if(value == null)
        {
            return ValidationResult.Success;
        }

        DateTime date = (DateTime)value;

        if(date <= DateTime.Now)
        {
            return new ValidationResult("must be in the future");
        }

        return ValidationResult.Success;
    }
}

Controllers/WeddingController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity; // need this for password hasher
using WeddingPlanner.Models;
using Microsoft.EntityFrameworkCore;

namespace WeddingPlanner.Controllers;

public class WeddingController : Controller
{
    private int? userid
    {
        get{return HttpContext.Session.GetInt32("UserId");}
    }

    private bool isLoggedIn
    {
        get
        {
            return userid != null;
        }
    }

    // the following context things are needed to inject the context service into the controller
    private MyContext _context;

    public WeddingController(MyContext context)
    {
        _context = context;
    }

    [HttpGet("/dashboard")]
    public IActionResult Dashboard()
    {
        if(!isLoggedIn || userid == null)
        {
            return RedirectToAction("Forms", "User");
        }

        List<Wedding> allWeddings = _context.Weddings.Include(t => t.WeddingCreator).Include(t => t.WeddingParticipants).ToList();
        // Console.WriteLine(allWeddings.Count);

        return View("AllWeddings", allWeddings);
    }

    [HttpGet("/weddings/new")]
    public IActionResult NewWedding()
    {
        if(!isLoggedIn)
        {
            return RedirectToAction("Forms", "User");
        }
        return View("NewWedding");
    }

    [HttpPost("/weddings/create")]
    public IActionResult CreateWedding(Wedding newWedding)
    {
        if(!isLoggedIn || userid == null)
        {
            return RedirectToAction("Forms", "User");
        }

        if(ModelState.IsValid == false)
        {
            return NewWedding();
        }

        newWedding.UserId = (int)userid;
        _context.Weddings.Add(newWedding);
        _context.SaveChanges();
        return RedirectToAction("Dashboard");
    }

    [HttpPost("/weddings/{weddingId}/attend")]
    public IActionResult Attend(int weddingId)
    {
        if(!isLoggedIn || userid == null)
        {
            return RedirectToAction("Forms", "User");
        }

        UserWeddingParticipation? existingParticipation = _context.UserWeddingParticipations.FirstOrDefault(uwp => uwp.UserId == (int)userid && uwp.WeddingId == weddingId);

        if(existingParticipation != null)
        {
            _context.Remove(existingParticipation);
        }
        else
        {
            UserWeddingParticipation newParticipation = new UserWeddingParticipation(){
                UserId = (int)userid,
                WeddingId = weddingId
            };
        _context.UserWeddingParticipations.Add(newParticipation);
        }
        _context.SaveChanges();

        return RedirectToAction("Dashboard");
    }

    [HttpGet("/weddings/{weddingId}")]
    public IActionResult OneWedding(int weddingId)
    {
        if(!isLoggedIn)
        {
            return RedirectToAction("Forms", "User");
        }
        Wedding? oneWedding = _context.Weddings.Include(wedding => wedding.WeddingParticipants).ThenInclude(uwp => uwp.WeddingAttendee).FirstOrDefault(wedding => wedding.WeddingId == weddingId);
        if(oneWedding == null)
        {
            return RedirectToAction("Dashboard");
        }
        return View("OneWedding", oneWedding);
    }
}

Views/Wedding/AllWeddings.cshtml
@if(Context.Session.GetInt32("UserId") != null)
    {
        <form asp-controller="User" asp-action="Logout"><button>Logout</button></form>
    }

<h1>Welcome to the Wedding Planner</h1>

<a href="/weddings/new" class="btn btn-outline-dark">New Wedding</a>

<table>
    <thead>
        <th>
            <tr>
                <td>Wedding</td>
                <td>Date</td>
                <td>Guest</td>
                <td>Actions</td>
            </tr>
        </th>
    </thead>
    <tbody>
        @foreach(Wedding wedding in Model)
        {
            <tr>
                @* the if statement helps get rid of a null error warning *@
                @if(wedding.WeddingCreator != null)
                {
                    <td>
                        <a asp-controller="Wedding" asp-action="OneWedding" asp-route-weddingId="@wedding.WeddingId">@wedding.WedderOne & @wedding.WedderTwo</a>
                    </td>
                    <td>@wedding.WeddingDate</td>
                    <td>@wedding.WeddingParticipants.Count</td>
                    <td>
                        @{
                            @* we want to see if any one already participating in the trip is already a user that is logged in *@
                            bool alreadyAttending = wedding.WeddingParticipants.Any(participant => participant.UserId == Context.Session.GetInt32("UserId"));
                            
                            <form asp-controller="Wedding" asp-action="Attend" asp-route-weddingId="@wedding.WeddingId">
                                <button>
                                    @if(alreadyAttending)
                                    {
                                        <span>Un-RSVP</span>
                                    }
                                    else
                                    {
                                        <span>RSVP</span>
                                    }
                                </button>
                            </form>
                        }
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

Views/Wedding/NewWedding.cshtml
@model Wedding;

<a href="/dashboard">Dashboard</a>

@if(Context.Session.GetInt32("UserId") != null)
    {
        <form asp-controller="User" asp-action="Logout"><button>Logout</button></form>
    }

<h1>Plan Your Wedding</h1>

<div class="column">
    <form asp-action="CreateWedding" asp-controller="Wedding" method="post">
        <span asp-validation-for="WedderOne"></span>
        <div class="formline mb-3">
            <label asp-for="WedderOne"></label>
            <input class="form-control-sm" asp-for="WedderOne">
        </div>
        <span asp-validation-for="WedderTwo"></span>
        <div class="formline mb-3">
            <label asp-for="WedderTwo"></label>
            <input class="form-control-sm" asp-for="WedderTwo">
        </div>
        <span asp-validation-for="WeddingDate"></span>
        <div class="formline mb-3">
            <label asp-for="WeddingDate"></label>
            <input class="form-control-sm" asp-for="WeddingDate">
        </div>
        <span asp-validation-for="WeddingAddress"></span>
        <div class="formline mb-3">
            <label asp-for="WeddingAddress"></label>
            <input class="form-control-sm" asp-for="WeddingAddress">
        </div>
        <button class="btn btn-outline-dark" type="submit">Create</button>
    </form>
</div>

Views/Wedding/OneWedding.cshtml
@model Wedding

<a href="/dashboard">Dashboard</a>

@if(Context.Session.GetInt32("UserId") != null)
    {
        <form asp-controller="User" asp-action="Logout"><button>Logout</button></form>
    }

<h1>@Model.WedderOne and @Model.WedderTwo's Wedding</h1>

<h3>Date: @Model.WeddingDate</h3>

<h3>Guests:</h3>
<ul>
    @foreach(UserWeddingParticipation attending in Model.WeddingParticipants)
    {
        if(attending.WeddingAttendee != null)
        {
            <li>@attending.WeddingAttendee.FirstName @attending.WeddingAttendee.LastName</li>
        }
    }
</ul>